### ISSUE TITLE
Support new data governance feature

### ISSUE THREAD

**Issue by randycoulman** [configcat/elixir-sdk#13]
And here comes the magic to handle our new datagovernance feature. Please adjust this with the same logic from here:
https://github.com/configcat/python-sdk/blob/master/configcatclient/configfetcher.py#L74

_Originally posted by @laliconfigcat in https://github.com/configcat/elixir-sdk/pull/2#discussion_r506360349_

**Comment by igorescobar** [comment]
Maybe start this one only after migrating to the `v5` format, right? #18

**Comment by laliconfigcat** [comment]
Yes, these settings will only be available in v5

**Comment by igorescobar** [comment]
Just to give you some progress on this. The code is mostly done but I'm still not sure about the current implementation tho (design-wise) and I'm still trying to figure it out the best way to test this. I haven't had a lot of time recently and that's why it is taking more time. I hope to get this done today.
